### ISSUE TITLE
No roles & permissions sub menu

### ISSUE THREAD

**Issue by Kristories** [itsmejoshua/novaspatiepermissions#2]
<img width="771" alt="Screen Shot 2022-04-26 at 17 59 09" src="https://user-images.githubusercontent.com/774338/165285871-2bb22187-19aa-4d21-92ad-25fe09975759.png">

Using Laravel Nova `v4.2.5` (Silver Surfer).

**Comment by jordansitbon** [comment]
Yes same issue...

**Comment by DevPlus31** [comment]
Getting same issue

**Comment by nickpoulos** [comment]
Same Issue but not even the top level menu?

**Comment by itsmejoshua** [comment]
Sorry for the delay hoping to have an update in a day or two there was no easy work around to the menu no longer displaying given I'm short on time - I've asked someone in my team to have a look and provide a fix.

**Comment by itsmejoshua** [comment]
A fix has been provided today, It's not where I want it to be, but for the short term it gets you easily to the roles/permissions page.
