### ISSUE TITLE
Strange Column/Button Names Appearing

### ISSUE THREAD

**Issue by nickpoulos** [itsmejoshua/novaspatiepermissions#5]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/3959529/166153152-eb9001a0-a3ac-4916-865e-4dab89e4d5e6.png">

I am seeing an issue where the button/column names are showing up as some sort of translation key or field name key?

**Laravel Version**: 9.9.0
**Laravel Nova**: 4.2.7
**Spatie Permissions**: 5.5.2

**Comment by novelnet** [comment]
I have the same issue, seems like the default translation do not work yet.

**Comment by itsmejoshua** [comment]
I'm not seeing any issues in relation to this I'm running the latest of all as well

**Comment by itsmejoshua** [comment]
My only guess is you are using a language other than EN, feel free to add your language happy to support other languages.

**Comment by novelnet** [comment]
Fixed the missing translations by loading the ServiceProvider manually:
```
'providers' => [
    ...,
    Itsmejoshua\Novaspatiepermissions\NovaSpatiePermissionsServiceProvider::class,
]
```

**Comment by itsmejoshua** [comment]
> Fixed the missing translations by loading the ServiceProvider manually:
> 
> ```
> 'providers' => [
>     ...,
>     Itsmejoshua\Novaspatiepermissions\NovaSpatiePermissionsServiceProvider::class,
> ]
> ```

Yes thank you our next release will include the required fix to autoload instead of manually adding
